services:
  pascalallen-postgres:
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#    env_file:
#      - .env
    build:
      context: internal/pascalallen/infrastructure/etc/postgres
    container_name: pascalallen-postgres
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - pascalallen

  pascalallen-rabbitmq:
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
#    env_file:
#      - .env
    build:
      context: internal/pascalallen/infrastructure/etc/rabbitmq
    hostname: pascalallen-rabbitmq
    container_name: pascalallen-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./internal/pascalallen/infrastructure/etc/rabbitmq:/etc/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 10s
      retries: 10
    networks:
      - pascalallen

  pascalallen-go:
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
#    env_file:
#      - .env
    build:
      context: .
    container_name: pascalallen-go
    ports:
      - "9990:9990"
    volumes:
      - .:/app:rw
    depends_on:
      pascalallen-postgres:
        condition: service_started
      pascalallen-rabbitmq:
        condition: service_healthy
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - pascalallen

networks:
  pascalallen:
    name: pascalallen

volumes:
  dbdata:
    driver: local
