services:
  pascalallen-postgres:
    env_file:
      - .env
    build:
      context: ./etc/postgres
    container_name: pascalallen-postgres
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - pascalallen

  pascalallen-rabbitmq:
    env_file:
      - .env
    build:
      context: ./etc/rabbitmq
    hostname: pascalallen-rabbitmq
    container_name: pascalallen-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./etc/rabbitmq:/etc/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 30s
      timeout: 30s
      retries: 10
    networks:
      - pascalallen

  pascalallen-go:
    env_file:
      - .env
    build:
      context: .
    container_name: pascalallen-go
    ports:
      - "9990:9990"
    volumes:
      - .:/app:rw
    depends_on:
      pascalallen-postgres:
        condition: service_started
      pascalallen-rabbitmq:
        condition: service_healthy
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - pascalallen

networks:
  pascalallen:
    name: pascalallen

volumes:
  dbdata:
    driver: local
