services:
  pascalallen-postgres:
    env_file:
      - .env
    build:
      context: ./etc/postgres
    container_name: pascalallen-postgres
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - pascalallen

  pascalallen-go:
    env_file:
      - .env
    build:
      context: .
    container_name: pascalallen-go
    ports:
      - "9990:9990"
    volumes:
      - .:/app:rw
    depends_on:
      - pascalallen-postgres
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - pascalallen

networks:
  pascalallen:
    name: pascalallen

volumes:
  dbdata:
    driver: local
