version: '3.9'

services:
  pascalallen-postgres:
    env_file:
      - .env
    build:
      context: ./etc/postgres
    container_name: pascalallen-postgres
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - pascalallen

  pascalallen-go:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile-production
    container_name: pascalallen-go
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/app:rw
    depends_on:
      - pascalallen-postgres
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      pascalallen:
        aliases:
          - pascalallen.com

networks:
  pascalallen:
    name: pascalallen

volumes:
  dbdata:
    driver: local
