apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres
  labels:
    name: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
