apiVersion: apps/v1
kind: Deployment
metadata:
  name: go
spec:
  replicas: 5
  selector:
    matchLabels:
      name: go
  template:
    metadata:
      labels:
        name: go
    spec:
      containers:
        - name: pascalallen-go
          image: pascalallen/pascalallen-go
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9990
          envFrom:
            - configMapRef:
                name: go
            - secretRef:
                name: go
