apiVersion: v1
kind: Service
metadata:
  name: go
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 9990
  selector:
    name: go

# 8. kubectl apply -f service.yml
