apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres
  labels:
    name: postgres
data:
  POSTGRES_DB: 'pascalallen'
  POSTGRES_USER: 'pascalallen'
  POSTGRES_PASSWORD: 'pa$$w0rd'

# 1. kubectl apply -f configmap.yml
