apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres
  labels:
    type: local
    name: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/lib/postgresql/data"

# 2. kubectl apply -f persistentvolume.yml
