apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    name: postgres
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:
    name: postgres

# 5. kubectl apply -f service.yml
