#!/usr/bin/env bash

# change to the project root
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$DIR"/.. || exit

# create bash environment variables from .env file
export "$(grep -v '^#' .env | xargs -d '\n')"

# change to main branch, if needed
BRANCH="$(git branch --show-current)"
if [ "$BRANCH" != "main" ]
then
  git checkout main -q
fi

# bring up environment, if changes have been made
GIT_STATUS="$(git status -s)"
if [ -n "$GIT_STATUS" ]
then
  git pull \
    && bin/down prod \
    && docker system prune -a -f \
    && docker builder prune -a -f \
    && bin/up prod \
    && bin/yarn ci \
    && bin/yarn build
fi

# send notification, if services are not running
DOCKER_STATUS="$(docker compose ps --status running --format "{{.Name}}")"
if [[ "$DOCKER_STATUS" != *"pascalallen-go"* ]] || [[ "$DOCKER_STATUS" != *"pascalallen-postgres"* ]]
then
  curl -H "Content-type: application/json" \
    --data '{"channel":"D01HKH4B145","blocks":[{"type":"section","text":{"type":"mrkdwn","text":"Deploy *_failed_*."}}]}' \
    -X POST "$SLACK_DM_URL"
fi
