#!/usr/bin/env bash

# change to the project root
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$DIR"/.. || exit

# change to main branch, if needed
BRANCH="$(git branch --show-current)"
if [ "$BRANCH" != "main" ]
then
  git checkout main -q
fi

# check git status
GIT_STATUS="$(git status -s)"
if [ "$GIT_STATUS" -ne 0 ]
then
  git pull \
    && bin/down prod \
    && docker builder prune -a -f \
    && bin/up prod \
    && bin/yarn ci \
    && bin/yarn build
fi

# check docker status
DOCKER_STATUS="$(docker compose ps --status running --format "{{.Name}}")"
if [[ "$DOCKER_STATUS" != *"pascalallen-go"* ]] || [[ "$DOCKER_STATUS" != *"pascalallen-postgres"* ]]
then
  curl -H "Content-type: application/json" \
    --data '{"channel":"D01HKH4B145","blocks":[{"type":"section","text":{"type":"mrkdwn","text":"Deploy *_failed_*."}}]}' \
    -X POST https://hooks.slack.com/services/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
fi
