// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/pascalallen/pascalallen.com/internal/pascalallen/infrastructure/providers"
)

import (
	_ "github.com/joho/godotenv/autoload"
)

// Injectors from wire.go:

func InitializeContainer() *Container {
	session := providers.NewDatabaseSession()
	permissionRepository := providers.NewPermissionRepository(session)
	roleRepository := providers.NewRoleRepository(session)
	userRepository := providers.NewUserRepository(session)
	seeder := providers.NewDatabaseSeeder(session, permissionRepository, roleRepository, userRepository)
	container := NewContainer(session, permissionRepository, roleRepository, userRepository, seeder)
	return container
}
