name: Yarn

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main ]

jobs:
  yarn-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Test that JavaScript dependencies can be installed with Yarn
        working-directory: ./client
        run: yarn install --frozen-lockfile